// generated by react-router-hono-server/dev
import { createHonoServer } from "react-router-hono-server/bun";
import { Hono } from "hono";

const app = new Hono();

app.get("/trpc", (c) => c.json({ msg: "hono is online" }));

export default await createHonoServer({ app });
