// generated by react-router-hono-server/dev
import { createHonoServer } from "react-router-hono-server/bun";
import { Hono } from "hono";
import { trpcServer } from "@hono/trpc-server";
import { appRouter } from "./globalRoute";

export const config = { runtime: "bun" };

const app = new Hono();

app.use(
  "/trpc/*",
  trpcServer({
    router: appRouter,
  })
);

export default await createHonoServer({ app });
